/**
 * src/lib/services/demoService.js
 * ─────────────────────────────────────────────────────────────────────────────
 * All business logic for the Demo Competition system.
 * Demo data is completely isolated from real affiliate data.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import prisma from '../prisma.js';

// ── Name pool (Moroccan market) ────────────────────────────────────────────────
const FIRST_NAMES = [
  'Youssef','Hamza','Omar','Amine','Karim','Mehdi','Rachid','Samir','Nabil','Khalid',
  'Tariq','Hassan','Mouad','Bilal','Hicham','Soufiane','Adil','Zakaria','Ismail','Younes',
  'Sara','Nadia','Fatima','Samira','Leila','Meryem','Houda','Zineb','Hajar','Imane',
  'Chaimae','Doha','Yasmina','Sanaa','Karima','Siham','Widad','Asmaa','Nawal','Btissam',
  'Ayoub','Ilyass','Walid','Ayman','Othmane','Driss','Morad','Reda','Tarik','Jawad',
];
const LAST_NAMES = [
  'Benaissa','El Amrani','Chaabi','Benali','Ouarrach','Akhtar','Bennis','Filali',
  'Berrada','Essaidi','Lazrak','Mrani','Tahiri','Ziani','Bennani','Alaoui','Skali',
  'Chraibi','Benkirane','Tazi','Hajji','Bouazzaoui','Fassi','Mansouri','Sentissi',
];
const AVATAR_COLORS = [
  '#6366f1','#8b5cf6','#ec4899','#f59e0b','#10b981','#3b82f6',
  '#ef4444','#14b8a6','#f97316','#84cc16','#06b6d4','#a855f7',
];

// ── Growth parameters ─────────────────────────────────────────────────────────
const GROWTH = {
  aggressive: { ordersRange: [4, 12], revenuePerOrder: [200, 500], teamGrowthChance: 0.4, cancelRate: 0.05 },
  consistent: { ordersRange: [2, 5],  revenuePerOrder: [120, 320], teamGrowthChance: 0.2, cancelRate: 0.10 },
  slow:       { ordersRange: [0, 2],  revenuePerOrder: [80,  200], teamGrowthChance: 0.1, cancelRate: 0.15 },
};

const SPEED_MULT = { slow: 0.4, medium: 1, fast: 2.8 };

const COMMISSION_RATE = 0.05; // 5% parent earns from team

function rand(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }
function randF(min, max) { return +(Math.random() * (max - min) + min).toFixed(2); }
function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }

// ── Leaderboard in-memory cache ───────────────────────────────────────────────
let _leaderboardCache = null;
let _leaderboardTs    = 0;
const LEADERBOARD_TTL = 60_000; // 60 s

export function invalidateDemoCache() {
  _leaderboardCache = null;
}

// ── Generate demo affiliates ──────────────────────────────────────────────────

export async function generateDemoAffiliates(count = 60) {
  // Clear existing demo data first
  await prisma.demoEarningsHistory.deleteMany();
  await prisma.demoStats.deleteMany();
  await prisma.demoAffiliate.deleteMany();

  const types  = ['aggressive', 'consistent', 'consistent', 'slow']; // weighted
  const created = [];

  for (let i = 0; i < count; i++) {
    const first = pick(FIRST_NAMES);
    const last  = pick(LAST_NAMES);
    const name  = `${first} ${last}`;
    const username = `demo_${first.toLowerCase()}${rand(10, 999)}`;

    const affiliate = await prisma.demoAffiliate.create({
      data: {
        name,
        username,
        avatarColor: pick(AVATAR_COLORS),
        growthType:  pick(types),
        stats: {
          create: {
            totalOrders:     rand(0, 30),
            totalRevenue:    randF(0, 9000),
            confirmedOrders: rand(0, 25),
            cancelledOrders: rand(0, 5),
            teamSize:        rand(0, 8),
            teamOrders:      rand(0, 20),
            teamRevenue:     randF(0, 5000),
            teamCommission:  0,
            todayOrders:     rand(0, 3),
            todayRevenue:    randF(0, 800),
          },
        },
      },
    });
    created.push(affiliate.id);
  }

  // Seed 7 days of history for each
  const now = new Date();
  for (const demoId of created) {
    const affiliate = await prisma.demoAffiliate.findUnique({
      where: { id: demoId },
      select: { growthType: true },
    });
    const g = GROWTH[affiliate.growthType];

    for (let d = 6; d >= 0; d--) {
      const date    = new Date(now);
      date.setDate(date.getDate() - d);
      date.setHours(0, 0, 0, 0);
      const orders   = rand(...g.ordersRange);
      const revenue  = orders > 0 ? orders * randF(...g.revenuePerOrder) : 0;
      const commission = +(revenue * COMMISSION_RATE).toFixed(2);
      await prisma.demoEarningsHistory.create({
        data: { demoAffiliateId: demoId, date, orders, revenue: +revenue.toFixed(2), commission },
      });
    }
  }

  // Recalculate teamCommission and ranks
  await recomputeRanks();

  // Ensure competition row exists
  await ensureCompetition();

  // Mark settings as generated
  await prisma.demoSettings.upsert({
    where:  { id: 'settings' },
    update: { autoGenerated: true },
    create: { id: 'settings', isEnabled: true, simulationSpeed: 'medium', autoGenerated: true },
  });

  invalidateDemoCache();
  return { generated: count };
}

// ── Ensure competition row ────────────────────────────────────────────────────

export async function ensureCompetition() {
  const existing = await prisma.demoCompetition.findUnique({ where: { id: 'current' } });
  if (existing) return existing;

  const start = new Date();
  start.setDate(1);
  start.setHours(0, 0, 0, 0);
  const end = new Date(start);
  end.setMonth(end.getMonth() + 1);

  return prisma.demoCompetition.create({
    data: { id: 'current', startDate: start, endDate: end, isActive: true, cycleNum: 1 },
  });
}

// ── Recalculate ranks ─────────────────────────────────────────────────────────

async function recomputeRanks() {
  const stats = await prisma.demoStats.findMany({
    orderBy: [{ totalOrders: 'desc' }, { totalRevenue: 'desc' }],
    select:  { id: true, demoAffiliateId: true, totalRevenue: true },
  });

  for (let i = 0; i < stats.length; i++) {
    await prisma.demoStats.update({
      where: { id: stats[i].id },
      data:  {
        teamCommission: +(stats[i].totalRevenue * COMMISSION_RATE).toFixed(2),
        rank: i + 1,
      },
    });
  }
}

// ── Simulate one tick ─────────────────────────────────────────────────────────

export async function simulateTick() {
  const settings = await getDemoSettings();
  if (!settings.isEnabled) return { skipped: true };

  const mult      = SPEED_MULT[settings.simulationSpeed] ?? 1;
  const affiliates = await prisma.demoAffiliate.findMany({
    where:   { isActive: true },
    include: { stats: true },
  });

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  for (const aff of affiliates) {
    if (!aff.stats) continue;
    const g       = GROWTH[aff.growthType];
    const orders  = Math.round(rand(...g.ordersRange) * mult);
    const revenue = orders > 0 ? +(orders * randF(...g.revenuePerOrder)).toFixed(2) : 0;
    const cancelled = Math.round(orders * g.cancelRate);
    const confirmed = orders - cancelled;

    // Team growth (probabilistic)
    const teamDelta = Math.random() < g.teamGrowthChance * mult ? rand(0, 2) : 0;
    const teamOrdersDelta = Math.round(orders * 0.3);
    const teamRevenueDelta = +(teamOrdersDelta * randF(100, 300)).toFixed(2);

    await prisma.demoStats.update({
      where: { demoAffiliateId: aff.id },
      data: {
        totalOrders:     { increment: orders },
        totalRevenue:    { increment: revenue },
        confirmedOrders: { increment: confirmed },
        cancelledOrders: { increment: cancelled },
        todayOrders:     { increment: orders },
        todayRevenue:    { increment: revenue },
        teamSize:        { increment: teamDelta },
        teamOrders:      { increment: teamOrdersDelta },
        teamRevenue:     { increment: teamRevenueDelta },
      },
    });

    // Upsert today's history row
    const existing = await prisma.demoEarningsHistory.findFirst({
      where: { demoAffiliateId: aff.id, date: today },
    });
    const commission = +(revenue * COMMISSION_RATE).toFixed(2);
    if (existing) {
      await prisma.demoEarningsHistory.update({
        where: { id: existing.id },
        data: {
          orders:     { increment: orders },
          revenue:    { increment: revenue },
          commission: { increment: commission },
        },
      });
    } else {
      await prisma.demoEarningsHistory.create({
        data: { demoAffiliateId: aff.id, date: today, orders, revenue, commission },
      });
    }
  }

  // Recalculate ranks + update lastSimAt
  await recomputeRanks();
  await prisma.demoSettings.upsert({
    where:  { id: 'settings' },
    update: { lastSimAt: new Date() },
    create: { id: 'settings', isEnabled: true, simulationSpeed: 'medium', lastSimAt: new Date() },
  });

  // Check if competition needs reset (30-day cycle)
  const comp = await prisma.demoCompetition.findUnique({ where: { id: 'current' } });
  if (comp && new Date() >= comp.endDate) {
    await resetCompetition(false); // silent reset
  }

  invalidateDemoCache();
  return { simulated: affiliates.length };
}

// ── Reset competition ─────────────────────────────────────────────────────────

export async function resetCompetition(clearHistory = true) {
  // Zero all stats
  await prisma.demoStats.updateMany({
    data: {
      totalOrders: 0, totalRevenue: 0, confirmedOrders: 0, cancelledOrders: 0,
      todayOrders: 0, todayRevenue: 0, teamOrders: 0, teamRevenue: 0,
      teamCommission: 0, rank: 0,
    },
  });

  if (clearHistory) {
    await prisma.demoEarningsHistory.deleteMany();
  }

  // Advance competition cycle
  const prev = await prisma.demoCompetition.findUnique({ where: { id: 'current' } });
  const start = new Date();
  start.setHours(0, 0, 0, 0);
  const end = new Date(start);
  end.setDate(end.getDate() + 30);

  await prisma.demoCompetition.upsert({
    where:  { id: 'current' },
    update: { startDate: start, endDate: end, cycleNum: { increment: 1 } },
    create: { id: 'current', startDate: start, endDate: end, isActive: true, cycleNum: 1 },
  });

  invalidateDemoCache();
  return { reset: true, cycle: (prev?.cycleNum ?? 0) + 1 };
}

// ── Leaderboard ───────────────────────────────────────────────────────────────

export async function getLeaderboard(limit = 20) {
  if (_leaderboardCache && Date.now() - _leaderboardTs < LEADERBOARD_TTL) {
    return _leaderboardCache.slice(0, limit);
  }

  const rows = await prisma.demoAffiliate.findMany({
    where:   { isActive: true },
    include: { stats: true },
    orderBy: { stats: { totalOrders: 'desc' } },
    take:    limit,
  });

  const data = rows.map((a, i) => ({
    id:          a.id,
    name:        a.name,
    username:    a.username,
    avatarColor: a.avatarColor,
    growthType:  a.growthType,
    rank:        i + 1,
    totalOrders:     a.stats?.totalOrders     ?? 0,
    totalRevenue:    a.stats?.totalRevenue    ?? 0,
    confirmedOrders: a.stats?.confirmedOrders ?? 0,
    cancelledOrders: a.stats?.cancelledOrders ?? 0,
    todayOrders:     a.stats?.todayOrders     ?? 0,
    todayRevenue:    a.stats?.todayRevenue    ?? 0,
    teamSize:        a.stats?.teamSize        ?? 0,
  }));

  _leaderboardCache = data;
  _leaderboardTs    = Date.now();
  return data.slice(0, limit);
}

// ── Affiliate details (lazy) ──────────────────────────────────────────────────

export async function getDemoAffiliateDetails(id) {
  const aff = await prisma.demoAffiliate.findUnique({
    where:   { id },
    include: {
      stats: true,
      earningsHistory: {
        orderBy: { date: 'asc' },
        take:    30,
      },
    },
  });
  if (!aff) return null;

  const s = aff.stats;
  return {
    id:          aff.id,
    name:        aff.name,
    username:    aff.username,
    avatarColor: aff.avatarColor,
    growthType:  aff.growthType,
    rank:        s?.rank ?? 0,
    // Main stats
    totalOrders:     s?.totalOrders     ?? 0,
    totalRevenue:    s?.totalRevenue    ?? 0,
    confirmedOrders: s?.confirmedOrders ?? 0,
    cancelledOrders: s?.cancelledOrders ?? 0,
    // Today
    todayOrders:  s?.todayOrders  ?? 0,
    todayRevenue: s?.todayRevenue ?? 0,
    // Team
    teamSize:       s?.teamSize       ?? 0,
    teamOrders:     s?.teamOrders     ?? 0,
    teamRevenue:    s?.teamRevenue    ?? 0,
    teamCommission: s?.teamCommission ?? 0,
    // History (last 30 days)
    earningsHistory: aff.earningsHistory.map((h) => ({
      date:       h.date,
      orders:     h.orders,
      revenue:    h.revenue,
      commission: h.commission,
    })),
  };
}

// ── Settings ──────────────────────────────────────────────────────────────────

export async function getDemoSettings() {
  const s = await prisma.demoSettings.findUnique({ where: { id: 'settings' } });
  return s ?? { id: 'settings', isEnabled: true, simulationSpeed: 'medium', lastSimAt: null, autoGenerated: false };
}

export async function saveDemoSettings(data) {
  const { isEnabled, simulationSpeed } = data;
  return prisma.demoSettings.upsert({
    where:  { id: 'settings' },
    update: { isEnabled, simulationSpeed },
    create: { id: 'settings', isEnabled, simulationSpeed },
  });
}

// ── Competition info ──────────────────────────────────────────────────────────

export async function getCompetitionInfo() {
  const comp  = await ensureCompetition();
  const total = await prisma.demoAffiliate.count({ where: { isActive: true } });
  const now   = new Date();
  const msLeft = comp.endDate.getTime() - now.getTime();
  const daysLeft = Math.max(0, Math.ceil(msLeft / 86_400_000));

  return {
    startDate: comp.startDate,
    endDate:   comp.endDate,
    cycleNum:  comp.cycleNum,
    daysLeft,
    totalParticipants: total,
  };
}
